### ISSUE TITLE
A Javascript book worth reading

### ISSUE THREAD

**Issue by hkasera** [WomenWhoCode/guidelines-resources#31]
I found this book on github called [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS). It explains very clearly and conceptually the fundamentals of Javascript and I believe every Javascript Developer must read this.

I would like to raise a pull request for the same. Is this a welcome contribution right now?

**Comment by jig08** [comment]
Hi @hkasera , I believe there should not be any reason why we shouldn't include it in our resources if the book is helpful in learning the fundamentals of JS :)

**Comment by hkasera** [comment]
You are absolutely correct @jig08 :+1:  . I will send a PR for this. Thanks :smile:

**Comment by jig08** [comment]
Great .
